version: '3.7'

services:
    ng-app-prod:
        container_name: xschools-ng-app-prod
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '4000:80'
        extra_hosts:
            - "host.docker.internal:host-gateway"
